Fix for dependency cycle in module.pp
When deploying custom modules using hiera, the module.pp introduces a
dependency cycle. See the error below:

Error: Could not apply complete catalog: Found 1 dependency cycle:
(Exec[/usr/share/selinux/local_test-module.pp] =>
Selinux::Module[test-module] => Class[Selinux] =>
Selinux::Module[test-module] =>
Exec[/usr/share/selinux/local_test-module.pp])

Changed "require ::selinux" to "include ::selinux"