Adapt required rubocop config change
Workaround for warning/errors:

/voxpupuli/puppet-selinux/.rubocop.yml: Lint/Eval has the wrong namespace - should be Security
Error: The `Style/MethodCallParentheses` cop has been renamed to `Style/MethodCallWithoutArgsParentheses`.